apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: plant_analytics
            - name: POSTGRES_INITDB_ARGS
              value: --encoding=UTF-8
            - name: POSTGRES_PASSWORD
              value: plantpassword123
            - name: POSTGRES_USER
              value: plantuser
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U plantuser -d plant_analytics
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: plant-analytics-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-cm1
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - configMap:
            name: postgres-cm1
          name: postgres-cm1
