{{- if .Values.services.authService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plant-analytics-platform.auth-service.fullname" . }}
  labels:
    {{- include "plant-analytics-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.services.authService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plant-analytics-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth-service
  template:
    metadata:
      labels:
        {{- include "plant-analytics-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: auth-service
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-auth-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.services.authService.image.repository }}:{{ .Values.services.authService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.authService.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.services.authService.env.NODE_ENV | quote }}
            - name: JWT_SECRET
              value: {{ .Values.services.authService.env.JWT_SECRET | quote }}
            - name: POSTGRES_HOST
              value: {{ include "plant-analytics-platform.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
          livenessProbe:
            httpGet:
              path: /auth/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /auth/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.services.authService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}